host: thestandardlibrary.com
author: Daniel Huckstep
author_email: darkhelmet@darkhelmetlive.com
go:
    price: 39
    pages: 108
    chapters: 8
    total_chapters: 40
    sample: http://samples.leanpub.com/go-thestdlib-sample.pdf
