host: thestandardlibrary.com
author: Daniel Huckstep
author_email: darkhelmet@darkhelmetlive.com
title: The Standard Library
go:
    price: 39
    pages: 189
    chapters: 16
    total_chapters: 40
    title: Go, The Standard Library
    sample: http://samples.leanpub.com/go-thestdlib-sample.pdf
    code: https://dl.dropboxusercontent.com/u/521811/the-standard-library/go/go-thestdlib.zip
    leanpub: https://leanpub.com/go-thestdlib

