host: thestandardlibrary.com
author: Daniel Huckstep
author_email: darkhelmet@darkhelmetlive.com
title: The Standard Library
go:
    price: 39
    pages: 280
    chapters: 24
    total_chapters: 40
    title: Go, The Standard Library
    sample: http://samples.leanpub.com/go-thestdlib-sample.pdf
    leanpub: https://leanpub.com/go-thestdlib

